[build-system]
requires = [ "setuptools"]

[project]
name = "ottemplate-python"
version = "0.1"
description = "Template"
readme = "README.rst"
dependencies = [ "numpydoc","sphinx_gallery", "sphinx", "matplotlib", "openturns",]
