# -*- coding: utf-8 -*-
#
# ottemplate documentation build configuration file, created by
# sphinx-quickstart on Fri Jun 19 15:57:39 2015.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os
from distutils.version import LooseVersion
import sphinx
import sphinx_gallery
import subprocess

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('../'))

# -- General configuration ------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.intersphinx',
    'sphinx.ext.autosummary',
    'sphinx.ext.coverage',
    'numpydoc',
    'sphinx_gallery.gen_gallery'
]

sphinx_gallery_conf = {
    'examples_dirs': ['examples'],  # path to
    # example scripts
    'gallery_dirs': ['auto_example'],
     'filename_pattern': '/plot_',
    'run_stale_examples': True,
    'show_signature': False,
    # directory where function/class granular galleries are stored
    'backreferences_dir'  : 'gen_modules/backreferences',

    # Modules for which function/class level galleries are created.
    'doc_module'          : ('openturns'),

    # objects to exclude from implicit backreferences. The default option
    # is an empty set, i.e. exclude nothing.
    'exclude_implicit_doc': {},
}

if LooseVersion(sphinx.__version__) >= LooseVersion('1.8'):
    autodoc_default_options = {'members': None, 'inherited-members': None, 'exclude-members': 'thisown'}
else:
    autodoc_default_flags =  ['members', 'inherited-members']

try:
    import sphinx.ext.imgmath
    extensions.append('sphinx.ext.imgmath')
    imgmath_latex_preamble = r'\usepackage{{{0}math_notations}}'.format(
        os.path.dirname(__file__) + os.sep)
    imgmath_use_preview = True
    if subprocess.call('dvisvgm -V', shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE) == 0:
        imgmath_image_format = 'svg'
    # embed image files inside html
    imgmath_embed = True
except ImportError:
    extensions.append('sphinx.ext.pngmath')
    pngmath_latex_preamble = r'\usepackage{{{0}math_notations}}'.format(
        os.path.dirname(__file__) + os.sep)
    # The next option is used for smart-alignment of math images on the text.
    # It only works when the preview-latex package is installed.
    # See http://sphinx-doc.org/latest/ext/math.html#confval-pngmath_use_preview
    pngmath_use_preview = True

extensions.append('matplotlib.sphinxext.plot_directive')

intersphinx_mapping = {'python': (
    'http://openturns.github.io/openturns/1.18', 'openturns-objects.inv')}
autosummary_generate = True

numpydoc_show_class_members = True
numpydoc_class_members_toctree = False


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = ['.rst']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'ottemplate'
copyright = u'2005-2022 Airbus-EDF-IMACS-ONERA-Phimeca'
# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.1'
# The full version, including alpha/beta/rc tags.
release = '0.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True


# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = False

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'friendly' # sphinx

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------
# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'openturns'
html_sourcelink_suffix = ''

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}
#import alabaster
html_theme_path = ['themes']

html_sidebars = {'**': ['globaltoc.html', 'relations.html', 'sourcelink.html', 'searchbox.html']}

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = 'None'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%b %d, %Y'

# Output file base name for HTML help builder.
#htmlhelp_basename = 'ottemplatedoc'

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# -- Options for LaTeX output ---------------------------------------------
latex_preamble = r'''
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{expdlist}
\usepackage{math_notations}
\usepackage{stackrel}
\let\latexdescription=\description
\def\description{\latexdescription{}{} \breaklabel}
\DeclareMathOperator*{\argmin}{Argmin}
'''


latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',
    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    'preamble': latex_preamble,
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    ('index', 'ottemplate.tex', u'ottemplate Documentation',
     u'Airbus-EDF-IMACS-Phimeca-ONERA', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'ottemplate', u'ottemplate Documentation',
     [u'Airbus-EDF-IMACS-Phimeca-ONERA'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output ------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    ('index', 'ottemplate', u'ottemplate Documentation',
   u'Airbus-EDF-IMACS-Phimeca-ONERA', 'ottemplate', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False
